language: cpp

compiler:
  - clang
  - gcc

sudo: required

install:
  - sudo apt install libsfml-dev
# TODO: Set up Travis for liblib and just download the release
  - git clone https://github.com/pixelherodev/liblib.git
  - cd liblib
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make install
  - cd ../..
  - git clone https://github.com/pixelherodev/z80cpp
  - cd z80cpp
  - git checkout interrupt
  - cp ../misc/z80cppCMakeLists.txt CMakeLists.txt
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make install
  - cd ../..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -kj4
