# AUTOGENERATED FILE; DO NOT MODIFY (use `build.py` instead)
CFLAGS+=-DPROJECT_VERSION=0.2.0 -DSOKOL_GLCORE33 -D_POSIX_C_SOURCE=200809L -O2 -Wall -pedantic -std=c99
CXXFLAGS+=-DPROJECT_VERSION=0.2.0 -DSOKOL_GLCORE33 -D_POSIX_C_SOURCE=200809L -O2 -Wall -pedantic -std=c++11
LDFLAGS+=-lX11 -lXi -lXcursor -lGL -ldl -lstdc++ -lm -pthread
INCLUDES+=-Ilib/ -Ilib/cimgui/

.PHONY: default run all Zany80
default: run

run: ./build/Zany80
	./build/Zany80

all: sokol cimgui stb rapidxml TextEditor scas z80e Zany80

HEADERS=lib/TextEditor/TextEditor.h lib/cimgui/cimgui.h lib/cimgui/imconfig.h lib/cimgui/imgui.h lib/cimgui/imgui_internal.h lib/cimgui/imstb_rectpack.h lib/cimgui/imstb_textedit.h lib/cimgui/imstb_truetype.h lib/rapidxml/rapidxml.hpp lib/rapidxml/rapidxml_iterators.hpp lib/rapidxml/rapidxml_print.hpp lib/rapidxml/rapidxml_utils.hpp lib/sokol/sokol_app.h lib/sokol/sokol_args.h lib/sokol/sokol_audio.h lib/sokol/sokol_fetch.h lib/sokol/sokol_gfx.h lib/sokol/sokol_glue.h lib/sokol/sokol_time.h lib/sokol/util/sokol_debugtext.h lib/sokol/util/sokol_fontstash.h lib/sokol/util/sokol_gfx_imgui.h lib/sokol/util/sokol_gl.h lib/sokol/util/sokol_imgui.h lib/sokol/util/sokol_memtrack.h lib/stb/stb_ds.h lib/z80e/cpu.h lib/z80e/debugger/commands.h lib/z80e/debugger/debugger.h lib/z80e/debugger/hooks.h lib/z80e/debugger/keys.h lib/z80e/disassembler/disassemble.h lib/z80e/log/log.h lib/z80e/registers.h lib/z80e/runloop/runloop.h lib/z80e/ti/asic.h lib/z80e/ti/hardware/flash.h lib/z80e/ti/hardware/interrupts.h lib/z80e/ti/hardware/keyboard.h lib/z80e/ti/hardware/link.h lib/z80e/ti/hardware/memorymapping.h lib/z80e/ti/hardware/speed.h lib/z80e/ti/hardware/status.h lib/z80e/ti/hardware/t6a04.h lib/z80e/ti/hardware/timers.h lib/z80e/ti/memory.h lib/z80e/ti/ti.h src/XML.h src/editor.h src/global.h src/graphics.h src/license.h src/ring_buffer.h src/scas.h src/serial.h src/z80.h src/z80_tab.h src/zexall.h
build/obj/%.o: %.c $(HEADERS)
	$(CC) $< $(CFLAGS) $(EXTRA_CFLAGS) $(INCLUDES) -c -o $@
build/obj/%.o: %.cpp $(HEADERS)
	$(CXX) $< $(CXXFLAGS) $(EXTRA_CXXFLAGS) $(INCLUDES) -c -o $@

### TARGET: TextEditor

TextEditor_OBJECTS = build/obj/lib/TextEditor/TextEditor.o
$(TextEditor_OBJECTS): EXTRA_CFLAGS := 
$(TextEditor_OBJECTS): EXTRA_CXXFLAGS := 

TextEditor_HEADERS = lib/TextEditor/TextEditor.h


### TARGET: cimgui

cimgui_OBJECTS = build/obj/lib/cimgui/cimgui.o build/obj/lib/cimgui/imgui.o build/obj/lib/cimgui/imgui_demo.o build/obj/lib/cimgui/imgui_draw.o build/obj/lib/cimgui/imgui_widgets.o
$(cimgui_OBJECTS): EXTRA_CFLAGS := 
$(cimgui_OBJECTS): EXTRA_CXXFLAGS := 

cimgui_HEADERS = lib/cimgui/cimgui.h lib/cimgui/imconfig.h lib/cimgui/imgui.h lib/cimgui/imgui_internal.h lib/cimgui/imstb_rectpack.h lib/cimgui/imstb_textedit.h lib/cimgui/imstb_truetype.h


### TARGET: rapidxml

rapidxml_OBJECTS = 
$(rapidxml_OBJECTS): EXTRA_CFLAGS := 
$(rapidxml_OBJECTS): EXTRA_CXXFLAGS := 

rapidxml_HEADERS = lib/rapidxml/rapidxml.hpp lib/rapidxml/rapidxml_iterators.hpp lib/rapidxml/rapidxml_print.hpp lib/rapidxml/rapidxml_utils.hpp


### TARGET: scas

scas_OBJECTS = build/obj/lib/scas/assembler/assembler.o build/obj/lib/scas/assembler/directives.o build/obj/lib/scas/assembler/privatize.o build/obj/lib/scas/common/errors.o build/obj/lib/scas/common/expression.o build/obj/lib/scas/common/format.o build/obj/lib/scas/common/functions.o build/obj/lib/scas/common/hashtable.o build/obj/lib/scas/common/instructions.o build/obj/lib/scas/common/io.o build/obj/lib/scas/common/list.o build/obj/lib/scas/common/match.o build/obj/lib/scas/common/md5.o build/obj/lib/scas/common/objects.o build/obj/lib/scas/common/operators.o build/obj/lib/scas/common/readline.o build/obj/lib/scas/common/stack.o build/obj/lib/scas/common/stringop.o build/obj/lib/scas/linker/8xp.o build/obj/lib/scas/linker/bin.o build/obj/lib/scas/linker/linker.o build/obj/lib/scas/linker/merge.o
$(scas_OBJECTS): EXTRA_CFLAGS := -Ilib/scas/include
$(scas_OBJECTS): EXTRA_CXXFLAGS := 

scas_HEADERS = 


### TARGET: sokol

sokol_OBJECTS = build/obj/lib/sokol/sokol.o build/obj/lib/sokol/sokol_cpp.o
$(sokol_OBJECTS): EXTRA_CFLAGS := 
$(sokol_OBJECTS): EXTRA_CXXFLAGS := 

sokol_HEADERS = lib/sokol/sokol_app.h lib/sokol/sokol_args.h lib/sokol/sokol_audio.h lib/sokol/sokol_fetch.h lib/sokol/sokol_gfx.h lib/sokol/sokol_glue.h lib/sokol/sokol_time.h lib/sokol/util/sokol_debugtext.h lib/sokol/util/sokol_fontstash.h lib/sokol/util/sokol_gfx_imgui.h lib/sokol/util/sokol_gl.h lib/sokol/util/sokol_imgui.h lib/sokol/util/sokol_memtrack.h


### TARGET: stb

stb_OBJECTS = build/obj/lib/stb/stb_ds.o
$(stb_OBJECTS): EXTRA_CFLAGS := 
$(stb_OBJECTS): EXTRA_CXXFLAGS := 

stb_HEADERS = lib/stb/stb_ds.h


### TARGET: z80e

z80e_OBJECTS = build/obj/lib/z80e/cpu.o build/obj/lib/z80e/debugger/commands/commands.o build/obj/lib/z80e/debugger/commands/disassemble.o build/obj/lib/z80e/debugger/commands/dump_lcd.o build/obj/lib/z80e/debugger/commands/hexdump.o build/obj/lib/z80e/debugger/commands/link.o build/obj/lib/z80e/debugger/commands/load_register.o build/obj/lib/z80e/debugger/commands/on.o build/obj/lib/z80e/debugger/commands/ports.o build/obj/lib/z80e/debugger/commands/press_key.o build/obj/lib/z80e/debugger/commands/print_expression.o build/obj/lib/z80e/debugger/commands/print_mappings.o build/obj/lib/z80e/debugger/commands/print_registers.o build/obj/lib/z80e/debugger/commands/release_key.o build/obj/lib/z80e/debugger/commands/run.o build/obj/lib/z80e/debugger/commands/stack.o build/obj/lib/z80e/debugger/commands/stop.o build/obj/lib/z80e/debugger/commands/tap_key.o build/obj/lib/z80e/debugger/commands/timers.o build/obj/lib/z80e/debugger/commands/turn_on.o build/obj/lib/z80e/debugger/commands/unhalt.o build/obj/lib/z80e/debugger/debugger.o build/obj/lib/z80e/debugger/hooks.o build/obj/lib/z80e/disassembler/disassemble.o build/obj/lib/z80e/log/log.o build/obj/lib/z80e/registers.o build/obj/lib/z80e/runloop/runloop.o build/obj/lib/z80e/ti/asic.o build/obj/lib/z80e/ti/hardware/flash.o build/obj/lib/z80e/ti/hardware/interrupts.o build/obj/lib/z80e/ti/hardware/keyboard.o build/obj/lib/z80e/ti/hardware/link.o build/obj/lib/z80e/ti/hardware/memorymapping.o build/obj/lib/z80e/ti/hardware/speed.o build/obj/lib/z80e/ti/hardware/status.o build/obj/lib/z80e/ti/hardware/t6a04.o build/obj/lib/z80e/ti/hardware/timers.o build/obj/lib/z80e/ti/memory.o
$(z80e_OBJECTS): EXTRA_CFLAGS := 
$(z80e_OBJECTS): EXTRA_CXXFLAGS := 

z80e_HEADERS = lib/z80e/cpu.h lib/z80e/debugger/commands.h lib/z80e/debugger/debugger.h lib/z80e/debugger/hooks.h lib/z80e/debugger/keys.h lib/z80e/disassembler/disassemble.h lib/z80e/log/log.h lib/z80e/registers.h lib/z80e/runloop/runloop.h lib/z80e/ti/asic.h lib/z80e/ti/hardware/flash.h lib/z80e/ti/hardware/interrupts.h lib/z80e/ti/hardware/keyboard.h lib/z80e/ti/hardware/link.h lib/z80e/ti/hardware/memorymapping.h lib/z80e/ti/hardware/speed.h lib/z80e/ti/hardware/status.h lib/z80e/ti/hardware/t6a04.h lib/z80e/ti/hardware/timers.h lib/z80e/ti/memory.h lib/z80e/ti/ti.h


### TARGET: Zany80

Zany80: build/Zany80

Zany80_OBJECTS = build/obj/src/XML.o build/obj/src/editor.o build/obj/src/graphics.o build/obj/src/graphics_legacy.o build/obj/src/license.o build/obj/src/main.o build/obj/src/ring_buffer.o build/obj/src/scas.o build/obj/src/serial.o build/obj/src/z80.o build/obj/src/z80_tab.o build/obj/src/zexall.o
$(Zany80_OBJECTS): EXTRA_CFLAGS := 
$(Zany80_OBJECTS): EXTRA_CXXFLAGS := 

Zany80_HEADERS = src/XML.h src/editor.h src/global.h src/graphics.h src/license.h src/ring_buffer.h src/scas.h src/serial.h src/z80.h src/z80_tab.h src/zexall.h

build/Zany80: $(Zany80_OBJECTS)  $(TextEditor_OBJECTS) $(cimgui_OBJECTS) $(rapidxml_OBJECTS) $(scas_OBJECTS) $(sokol_OBJECTS) $(stb_OBJECTS) $(z80e_OBJECTS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^
