# AUTOGENERATED FILE; DO NOT MODIFY (use `build.py` instead)
CFLAGS+=-DPROJECT_VERSION=0.2.0 -DSOKOL_GLCORE33 -O2 -Wall -Werror -Wextra -Wno-error=deprecated-declarations -Wno-error=missing-field-initializers -Wno-error=pedantic -Wno-error=reorder -Wno-error=unused-parameter -falign-functions=32 -march=native -mtune=native -pedantic -std=c99
CXXFLAGS+=-DPROJECT_VERSION=0.2.0 -DSOKOL_GLCORE33 -O2 -Wall -Werror -Wextra -Wno-error=deprecated-declarations -Wno-error=missing-field-initializers -Wno-error=pedantic -Wno-error=reorder -Wno-error=unused-parameter -falign-functions=32 -march=native -mtune=native -pedantic -std=c++11
LDFLAGS+=-lGL -lX11 -ldl -lstdc++
INCLUDES+=-Ilib/ -Ilib/cimgui/

.PHONY: default all Zany80
default: Zany80
	./build/Zany80

all: sokol cimgui stb TextEditor Zany80

HEADERS=lib/TextEditor/TextEditor.h lib/cimgui/cimgui.h lib/cimgui/imconfig.h lib/cimgui/imgui.h lib/cimgui/imgui_internal.h lib/cimgui/imstb_rectpack.h lib/cimgui/imstb_textedit.h lib/cimgui/imstb_truetype.h lib/sokol/sokol_app.h lib/sokol/sokol_args.h lib/sokol/sokol_audio.h lib/sokol/sokol_fetch.h lib/sokol/sokol_gfx.h lib/sokol/sokol_time.h lib/sokol/util/sokol_fontstash.h lib/sokol/util/sokol_gfx_imgui.h lib/sokol/util/sokol_gl.h lib/sokol/util/sokol_imgui.h lib/stb/stb_ds.h
build/obj/%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) $(INCLUDES) $< -c -o $@
build/obj/%.o: %.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) $(INCLUDES) $< -c -o $@

### TARGET: TextEditor

TextEditor_OBJECTS = build/obj/lib/TextEditor/TextEditor.o

TextEditor_HEADERS = lib/TextEditor/TextEditor.h


### TARGET: cimgui

cimgui_OBJECTS = build/obj/lib/cimgui/cimgui.o build/obj/lib/cimgui/imgui.o build/obj/lib/cimgui/imgui_demo.o build/obj/lib/cimgui/imgui_draw.o build/obj/lib/cimgui/imgui_widgets.o

cimgui_HEADERS = lib/cimgui/cimgui.h lib/cimgui/imconfig.h lib/cimgui/imgui.h lib/cimgui/imgui_internal.h lib/cimgui/imstb_rectpack.h lib/cimgui/imstb_textedit.h lib/cimgui/imstb_truetype.h


### TARGET: sokol

sokol_OBJECTS = build/obj/lib/sokol/sokol.o build/obj/lib/sokol/sokol_cpp.o

sokol_HEADERS = lib/sokol/sokol_app.h lib/sokol/sokol_args.h lib/sokol/sokol_audio.h lib/sokol/sokol_fetch.h lib/sokol/sokol_gfx.h lib/sokol/sokol_time.h lib/sokol/util/sokol_fontstash.h lib/sokol/util/sokol_gfx_imgui.h lib/sokol/util/sokol_gl.h lib/sokol/util/sokol_imgui.h


### TARGET: stb

stb_OBJECTS = build/obj/lib/stb/stb_ds.o

stb_HEADERS = lib/stb/stb_ds.h


### TARGET: Zany80

Zany80: build/Zany80

Zany80_OBJECTS = build/obj/src/graphics.o build/obj/src/graphics_legacy.o build/obj/src/main.o build/obj/src/ring_buffer.o build/obj/src/serial.o

Zany80_HEADERS = 

build/Zany80: $(Zany80_OBJECTS)  $(TextEditor_OBJECTS) $(cimgui_OBJECTS) $(sokol_OBJECTS) $(stb_OBJECTS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^
