---
platform: emscripten 
generator: Unix Makefiles
build_tool: make
build_type: Release
cmake-toolchain: emscripten.toolchain.cmake
defines:
    FIPS_NO_ASSERTS_IN_RELEASE: ON
    FIPS_EMSCRIPTEN_USE_FS: ON
    FIPS_EMSCRIPTEN_LOCALIZE: ON
