---
platform: emscripten 
generator: Unix Makefiles
build_tool: make
build_type: Debug
cmake-toolchain: emscripten.toolchain.cmake
defines:
    FIPS_EMSCRIPTEN_USE_FS: ON
    FIPS_EMSCRIPTEN_USE_WASM: OFF
    FIPS_EMSCRIPTEN_ALLOW_MEMORY_GROWTH: OFF
